### ISSUE TITLE
StochDynamicProgramming.jl

### ISSUE THREAD

**Issue by odow** [blegat/StochasticDualDynamicProgramming.jl#1]
Hey @blegat, have you seen this? https://github.com/JuliaOpt/StochDynamicProgramming.jl

**Comment by blegat** [comment]
Thanks for the heads up, I didn't see StochDynamicProgramming when I started this package (see [here](https://github.com/StructJuMP/StructJuMP.jl/issues/10)). A few months ago I saw it. It seems unfortunate that we created 2 packages with apparently exactly the same goal but I thing that they are complementary and with a little bit of generic interfaces they can work together.

**Comment by odow** [comment]
Somewhat surprisingly, there are actually quite a few (I know of at least four) implementations of SDDP being developed in Julia...

I don't fully understand the code but it's a nice idea to leverage StructJuMP.

**Comment by blegat** [comment]
Could you giveca link to the two other ones ?

**Comment by odow** [comment]
Unfortunately they're not public projects

**Comment by blegat** [comment]
What don't you understand in the implementation ? I will add a doc in the future and it would help to know what would be helpful to say

**Comment by odow** [comment]
A schematic layout of how the subproblems are laid out/stuctured via StructJuMP would be good.

I haven't delved into the code too deeply though...

**Comment by blegat** [comment]
Could you just tell who are the dev of the two private implementations ?

**Comment by odow** [comment]
Ha! I have one, and PSR are working on another https://github.com/JuliaOpt/MathProgBase.jl/issues/139#issue-197202945

**Comment by blegat** [comment]
Oh I see. I also saw @joaquimg's comment but I wasn't sure you were talking about that one.
Are you planning to make yours public at some point ?

**Comment by blegat** [comment]
The idea I have to make the different SDDP solvers work together is to have a modular framework. That is, split the SDDP algorithm in independent parts. The use could then use parts from different packages and still get a working SDDP implementation.
Those different parts could be

* The core : The main function that is called and that is using the other parts.
* A termination criterion : Those could also be mixed with `||` and `&&`. For instance, you could do `IterLimit(max=100) || (Pereira(2) && IterLimit(min=10))` which would stop after 100 iterations or if the pereira coef wants to stop and at least 10 iterations have been done.
* A cut manager : Stores a set of cuts (so a polyhedron), after each solve, it gets the dual variables (giving hints of which cuts are useful) and it may remove cuts whenever he likes.
* An NLDS Model : Gets queried to add constraints, remove some, solve the problem, returns solution... For instance, StochDynamicProgramming.jl would implement an NLDS Model using JuMP and StochasticDualDynamicProgramming.jl would implement one using MathProgBase.
* A sampling method : Its input are the number of sample to take, the probabilities for each and the number of paths for each child. For instance, you could either take randomly each path with the probabilities, samples some path deterministically and then take the rest randomly (for instance, if the proba are 0.5 and 0.5 and there 11 samples. we can split 5/5 and then take the last one randomly). For the entropic cone, since I only care about feasibility cuts and that the graph is a bit messy, it makes sense to sample more where there are more path to have a good coverage.
* ...
